### ISSUE TITLE
get_userplaycount() always returning 0

### ISSUE THREAD

**Issue by falsovsky** [pylast/pylast#306] opened 2019-06-08 18:06 UTC
### What did you do?

Tried to get the user play count for a track.

### What did you expect to happen?

Get the correct value. 56 or more in this case.

### What actually happened?

Always returns 0.

### What versions of OS, Python and pylast are you using?

* Linux 5.2.0-rc3
* Python 3.7.3
* pylast 3.1.0

Please include **code** that reproduces the issue.

```python
>>> import pylast
>>> network = pylast.LastFMNetwork(api_key='xxx', api_secret='xxx')
>>> track = pylast.Track(artist='Slayer', title='Seasons in the Abyss', network=network, username='falso')
>>> track.get_userplaycount()
0
```

I also looked at the unit tests,  and it seems do be doing it the same way I do, but it its testing for a track that doesnt exist so probably always returns 0.

https://github.com/pylast/pylast/blob/6a1a5a450ef14feb82e87f22805434873ce55b6d/tests/test_track.py#L48-L60
If I make the API request on the browser:

http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=xxx&artist=Slayer&track=Seasons%20in%20the%20Abyss&username=falso&format=json

It returns the "userplaycount" attribute there, and its not 0.

---

Is this a bug, or I'm using it wrongly?

**Comment by LeonelF** [comment] 2019-06-12 09:27
I have the exact same problem, if you try the get_playcount() works fine, but the get_userplaycount() doesn't
`>>> track.get_playcount()
28136
`
I also did a manual request to the API and the values are there, so not an API problem.
`"playcount": "28136",
(...)
"userplaycount": "54",
`

**Comment by hugovk** [comment] 2019-06-12 10:42
This does look like a bug.

The track in the test [does exist](https://www.last.fm/music/Test+Artist/_/test+title), and the user account used for tests has played that hundreds of times, according to a direct API call, but it returns 0 through pylast. That misleadingly matches `>= 0`, so at least the test can be improved.

`artist.get_userplaycount()` also started failing recently (https://github.com/pylast/pylast/pull/305#issuecomment-498380714), so these could be due to Last.fm changes but I've not tracked it down yet.

**Comment by LeonelF** [comment] 2019-06-12 10:54
Well I can't tell if the API have been changed or not, I can only confirm that the API replies the value for the user playcount as you can confirm with the code below:
`import http.client

conn = http.client.HTTPConnection("ws.audioscrobbler.com")

payload = ""

conn.request("GET", "/2.0/?api_key=<YOURAPIKEY>&username=falso&format=json&method=track.getInfo&artist=Slayer&track=Seasons%20in%20the%20Abyss", payload)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))`

The user playcount at this moment is 58

**Comment by LeonelF** [comment] 2019-06-17 16:20
> This does look like a bug.

Any idea on what is happening?

**Comment by falsovsky** [comment] 2019-06-17 21:07
Based on the last.fm documentation, it seems that POST is **ONLY** used on WRITE methods, and GET on the rest. 

> https://www.last.fm/api/rest

From what I have debugged, it seems that pylast is using POST on all requests.

https://github.com/pylast/pylast/blob/46e4c0ec4caf2fb9d6f923e5a6f77e221e96483c/src/pylast/__init__.py#L940-L963

A quick PoC that makes all requests via GET mode (breaking all the write functionality).

```diff
--- ../../src/pylast/__init__.py        2019-06-17 20:51:29.638747546 +0100
+++ pylast.py   2019-06-17 21:59:30.546614481 +0100
@@ -930,13 +930,14 @@
         data = "&".join(data)

         headers = {
-            "Content-type": "application/x-www-form-urlencoded",
             "Accept-Charset": "utf-8",
             "User-Agent": "pylast" + "/" + __version__,
         }

         (host_name, host_subdir) = self.network.ws_server

+        ws_url = "https://" + host_name + host_subdir + "?" + data
+
         if self.network.is_proxy_enabled():
             conn = HTTPSConnection(
                 context=SSL_CONTEXT,
@@ -946,9 +947,8 @@

             try:
                 conn.request(
-                    method="POST",
-                    url="https://" + host_name + host_subdir,
-                    body=data,
+                    method="GET",
+                    url=ws_url,
                     headers=headers,
                 )
             except Exception as e:
@@ -958,7 +958,7 @@
             conn = HTTPSConnection(context=SSL_CONTEXT, host=host_name)

             try:
-                conn.request(method="POST", url=host_subdir, body=data, headers=headers)
+                conn.request(method="GET", url=ws_url, headers=headers)
             except Exception as e:
                 raise NetworkError(self.network, e)

@@ -974,7 +974,7 @@
         return response_text

     def execute(self, cacheable=False):
-        """Returns the XML DOM response of the POST Request from the server"""
+        """Returns the XML DOM response of the GET Request from the server"""

         if self.network.is_caching_enabled() and cacheable:
             response = self._get_cached_response()

```

I thought of a way to fix it. In the **_Request** class, add a new parameter called **request_type**  set by default to **GET**. And then on the methods of the last.fm API that need "WRITE" permission, when creating the **_Request**, set the **request_type** to **POST**.

And of course add all the glue needed to make the URL vs POST DATA.

**Comment by hugovk** [comment] 2019-06-17 21:12
Not yet. It may be due to the calls from pylast being made as an authenticated user, and why unauthenticated browser requests and https://github.com/pylast/pylast/issues/306#issuecomment-501222252 work. 

https://www.last.fm/api/show/track.getInfo says "This service does **not** require authentication" but I'm fairly sure it previously used to work *with* authentication.

**Comment by hugovk** [comment] 2019-06-17 21:52
@falsovsky Good find! 

I posted before seeing your reply. I just found this report of POST not working with track.getinfo too: https://getsatisfaction.com/lastfm/topics/track-getinfo-username-something-doesnt-return-the-users-play-count-and-loved-status

The docs don't explicitly say you must use GET for reads, only that you must use POST for writes, but now this reminds me of this old branch which for some reason was never merged (maybe because the issue was closed without a PR):

https://github.com/hugovk/pylast/commits/post_or_get
https://github.com/hugovk/pylast/commit/055ff90c3f23669a2ec4ff3255dad0075a030954
https://github.com/pylast/pylast/issues/142

Would you like to test out that change?

**Comment by falsovsky** [comment] 2019-06-17 22:12
@hugovk I've been debugging a bit more since your reply

I found out the following:

When doing a POST with the QUERY params everything works.

```sh
curl --request POST \
  --url 'https://ws.audioscrobbler.com/2.0/?api_key=XXX&username=falso&method=track.getInfo&artist=Slayer&track=Dittohead'
```

But when posting it as Form Data as pylast does:

```sh
curl --request POST \
  --url https://ws.audioscrobbler.com/2.0/ \
  --data artist=Slayer \
  --data track=Dittohead \
  --data username=falso \
  --data api_key=XXX\
  --data method=track.getInfo
```

We only get:

```
<?xml version="1.0" encoding="UTF-8" ?>
<lfm status="ok"></lfm>
```

**Comment by falsovsky** [comment] 2019-06-17 22:24
@hugovk 
It works !

Heres an updated diff:

```diff
--- ../src/pylast/__init__.py   2019-06-17 20:51:29.638747546 +0100
+++ pylast.py   2019-06-17 23:22:52.371755024 +0100
@@ -929,6 +929,13 @@
             data.append("=".join((name, url_quote_plus(_string(self.params[name])))))
         data = "&".join(data)

+        if "api_sig" in self.params.keys():
+            method = "POST"
+            url_parameters = ""
+        else:
+            method = "GET"
+            url_parameters = "?" + data
+
         headers = {
             "Content-type": "application/x-www-form-urlencoded",
             "Accept-Charset": "utf-8",
@@ -946,10 +953,8 @@

             try:
                 conn.request(
-                    method="POST",
-                    url="https://" + host_name + host_subdir,
-                    body=data,
-                    headers=headers,
+                    url="https://" + host_name + host_subdir + url_parameters,
+                    method=method, body=data, headers=headers
                 )
             except Exception as e:
                 raise NetworkError(self.network, e)
@@ -958,7 +963,9 @@
             conn = HTTPSConnection(context=SSL_CONTEXT, host=host_name)

             try:
-                conn.request(method="POST", url=host_subdir, body=data, headers=headers)
+                conn.request(
+                    url=host_subdir + url_parameters, body=data,
+                    method=method, headers=headers)
             except Exception as e:
                 raise NetworkError(self.network, e)

```

**Comment by LeonelF** [comment] 2019-06-18 07:30
I've just forked and fixed it with @falsovsky fix, and IT WORKS!

Great job @falsovsky !

**Comment by falsovsky** [comment] 2019-06-18 08:19
Hi @LeonelF , I just fixed the patch for the latest pylast version. The original author is @hugovk .

**Comment by LeonelF** [comment] 2019-06-18 08:27
Yhea, I know, I've forked the pylast from @hugovk and fixed with your suggestion to test it out, and confirmed that your elegant fix works like a charm.

**Comment by falsovsky** [comment] 2019-06-30 15:52
@hugovk any news about fixing this and making a new release?

**Comment by hugovk** [comment] 2019-06-30 17:45
Thanks for the ping.

I put the fix (https://github.com/pylast/pylast/commit/c215600dcb14050ae4596fe432fa79461c39e824) in a new branch https://github.com/pylast/pylast/tree/post_or_get2 but the test cases are still [failing](https://travis-ci.org/pylast/pylast/builds/547273483). The difference between what we tried in this thread and the test suite is we created a `network` using just an API key and secret, and the test suite also uses a username and password hash.

The following passes and prints out `4426` and `4362`:

```python
network = pylast.LastFMNetwork(
    api_key=API_KEY,
    api_secret=API_SECRET,
    # username=username,
    # password_hash=password_hash,
)


def artist_playcount():
    artist = pylast.Artist("Test Artist", network, username=username)

    playcount = artist.get_userplaycount()

    print(playcount)
    assert playcount > 0


def track_playcount():

    track = pylast.Track("Test artist", "test track", network, username=username)

    playcount = track.get_userplaycount()

    print(playcount)
    assert playcount > 0


artist_playcount()
track_playcount()
```

But uncommenting `username` and `password_hash` means `artist_playcount()` gives `pylast.WSError: Operation failed - Most likely the backend service failed. Please try again.` and `track_playcount()` prints `0`.

The username and password means an authenticated session is used, and therefore it does a POST instead of a GET.

I wanted to try and figure these out before releasing, but unfortunately I've not had time.

**Comment by falsovsky** [comment] 2019-07-22 10:52
I'll try to take a look into this @hugovk as you don't seem to have time to fix this. And this bug turns the library quite useless.

I'll try to find a way to make the change in a way that the tests still passes, if I manage to do it, I'll open a PR.

**Comment by hugovk** [comment] 2019-07-22 12:55
Thank you! It's probably worth reporting at https://getsatisfaction.com/lastfm/categories/lastfm_apps in case it's something at their end.

**Comment by falsovsky** [comment] 2019-08-28 10:12
ping @hugovk 

Will you ever fix this? This makes the library quite useless for my use case. Have you abandoned it?

Maybe I will try to use HTTP requests on my tool so that I get the info that I need from Last.FM.

**Comment by hugovk** [comment] 2019-08-28 10:28
Hello! Nope, not abandoned. You were going to take a look, did you get any time for that?

**Comment by hifiberry** [comment] 2019-09-25 11:59
Any news on this. I've been running into the same issue. GET requests work, but POST doesn't.

**Comment by falsovsky** [comment] 2019-09-26 09:53
Well, I've looked into trying to fix the library, and I would have to change most of the code to fix it correctly. That would be very hard for me as I'm not the original designer and I don't use all the features of the library, just the PlayCount.

What i'm doing is using @LeonelF fork that has my ghetto patch.

`pip install git+https://github.com/LeonelF/pylast.git#egg=pylast`

**Closed** 2019-09-26 10:08 UTC
